#!/usr/bin/env perl 

use 5.012;
use FASTX::Reader;
use Getopt::Long;
 
my $opt_barcodes = 'barcodes.txt';
my $opt_outdir = './split/';
GetOptions(
  'b|barcodes=s'   => \$opt_barcodes,
  'o|outdir=s'     => \$opt_outdir,
);

say STDERR "
 Split by barcodes
 -------------------------
 sc_getbarcodes.pl -b barcodes.txt -o output_dir FILES...

 
";
my %barcodes = ();

mkdir "$opt_outdir" || die " Unable to create output directory $opt_outdir\n";

open (my $I, '<', "$opt_barcodes") || die " Unable to read barcodes: $opt_barcodes\n";
my $opt_start = 0;
my $opt_len = 0;
while (my $l = readline($I) ) {
  chomp($l);
  my ($bc, $hits, $start, $len) = split /\t/, $l;
  if ($hits > 0) {
    open (my $o, '>', "$opt_outdir/$bc.fq") || die;
    $barcodes{$bc} = $o;
    $opt_start = $start;
    $opt_len = $len;
  } else {
    die "Invalid barcodes file. should be generated by sc_getbarcodes.pl\n";
  }
}


for my $file (@ARGV) {
  next if not -e "$file";
  say STDERR " * Parsing $file";
  my $R = FASTX::Reader->new( { filename => "$file" });
  my $counter = 0;
  while (my $s = $R->getRead() ) {
    $counter++;
    my $bc = substr($s->{seq}, $opt_start, $opt_len);
    next unless defined $barcodes{$bc};
    say { $barcodes{$bc} } '@', $s->{name}, "\n", $s->{seq}, "\n+\n", $s->{qual};
  }
  say STDERR "\t $counter reads parsed.";
}

 