#!/usr/bin/env python
"""
Split FASTA/FASTQ files into multiple files according to:
 * Number of desired files,
 * Number of sequences per file, or
 * Number of bases per file.
"""

# Compatibility notes:
# subprocess.devnull is new in Python 3.3.
from __future__ import print_function
__VERSION__ = "0.1.1"
import sys, os, re
import subprocess


DEFAULT_COUNTER_LEN = 5
class SplitOpt:
    def __init__(self, args):
        self.threads = int(args.threads) if args.threads is not None else 1
        self.verbose = True if args.verbose or args.debug else False
        self.debug   = args.debug
        self.char    = args.number_char if args.number_char is not None else '0'
        self.output_string = args.output
        self.prefix, self.num_len, self.suffix, self.format = self.parse_output_string()
        self.input = args.input
        self.compress = True if args.compress else True if self.output_string.endswith('.gz') else False
    
    def __str__(self):
        return "fu-split{input: %s, output:%s%s%s, " % (self.input, self.prefix, "X" * self.num_len, self.suffix) + "threads: %d, verbose: %s, compress: %s}" % (self.threads, self.verbose, self.compress)

    def getOutput(self, number):
        """
        Return the formatted output file name for a given number.
        """
        suffix = self.suffix if self.suffix is not None else ''
        prefix = self.prefix if self.prefix is not None else ''
        return prefix + str(number).zfill(self.num_len) + suffix

    def parse_output_string(self):
        """
        Parse the output string.
        """
        format = None
        if self.output_string is None:
            return None, None, None, None
        dirname, filename = os.path.split(self.output_string)
        m = re.match(r'^(.*?)(%s{3,})(.*)$' % self.char, filename)
        if ".fasta" in self.output_string or ".fa" in self.output_string:
            format = "--fasta"
        elif ".fastq" in self.output_string or ".fq" in self.output_string:
            format = "--fastq"
        if m is None:
            return self.output_string, DEFAULT_COUNTER_LEN, '', None
        else:
            return os.path.join(dirname, m.group(1)), len(m.group(2)), m.group(3), format

def checkSeqfuVersion(minver="1.13.0", verbose=False):
    cmd = ["seqfu", "--version"]
    try:
        p = subprocess.Popen(cmd, stdout=subprocess.PIPE, stderr=subprocess.PIPE)
        version = p.stdout.read().decode("utf-8").split("\n")[0].strip().split(".")

        if len(version) < 3:
            return False        

        if verbose:
            print("[cmd] seqfu version: %s" % '.'.join(version), file=sys.stderr)


        # Compare semver
        if version[0] < minver.split(".")[0]:
            return False
        elif version[0] == minver.split(".")[0]:
            if version[1] < minver.split(".")[1]:
                return False
            elif version[1] == minver.split(".")[1]:
                if version[2] < minver.split(".")[2]:
                    return False
                return True
        else:
            return True
    except Exception as e:
        print("Error: `seqfu` not found:", e, file=sys.stderr)
        return False

def parse_bases(bases):
    """
    Receive a number or number with suffix (kb, gb, tb)
    """
    if bases.isdigit():
        return int(bases)
    else:
        if bases.lower().endswith("b"):
            bases = bases[:-1]
        elif bases.lower().endswith("bp"):
            bases = bases[:-2]
        suffix = bases[-1].lower()

        if suffix == "k":
            return int(bases[:-1]) * 1000
        elif suffix == "m":
            return int(bases[:-1]) * 1000 * 1000
        elif suffix == "g":
            return int(bases[:-1]) * 1000 * 1000 * 1000
        elif suffix == "t":
            return int(bases[:-1]) * 1000 * 1000 * 1000 * 1000
        else:
            print("Error: Invalid base number: %s" % bases, file=sys.stderr)
            return int(bases)
def removeNone(list):
    return [x for x in list if x is not None]

def delFile(filename, verbose=False):
    if os.path.exists(filename):
        try:
            if verbose:
                print("[delete] rm %s" % filename, file=sys.stderr)
            os.remove(filename)
        except Exception as e:
            print("Error: Cannot remove file: %s" % filename, file=sys.stderr)
            print(e, file=sys.stderr)
            return False
    else:
        print("Error: File %s not found" % filename, file=sys.stderr)
        return False
def runcmds(cmd1, cmd2, output, opt):
    cmd1 = removeNone(cmd1)
    cmd2 = removeNone(cmd2)
    
    try:
        if opt.debug:
            print("[cmd] Running: %s" % ' '.join(cmd1), file=sys.stderr)
        e1 = subprocess.Popen(cmd1, stdout=subprocess.PIPE, stderr=subprocess.PIPE)
    except Exception as e:
        print("Error:", e, file=sys.stderr)
        return False

    if opt.compress:
        try:
            if opt.debug:
                print("[cmd] Running: %s and gzip" % ' '.join(cmd2), file=sys.stderr)
            e2   = subprocess.Popen(cmd2, stdin=e1.stdout, stdout=subprocess.PIPE, stderr=subprocess.PIPE)
            subprocess.Popen(["gzip", "-c"], stdin=e2.stdout, stderr=subprocess.PIPE, stdout=output).communicate()
        except Exception as e:
            print("Error:", e, file=sys.stderr)
            return False
    else:
        try:
            if opt.debug:
                print("[cmd] Running: %s" % ' '.join(cmd2), file=sys.stderr)
            subprocess.Popen(cmd2, stdin=e1.stdout, stderr=subprocess.PIPE, stdout=output).communicate()
        except Exception as e:
            print("Error:", e, file=sys.stderr)
            return False
    return True

def runSingleCommand(cmd1, output, opt):
    cmd1 = removeNone(cmd1)
    
    if opt.compress:
        try:
            if opt.debug:
                print("[cmd] Running: %s and gzip" % ' '.join(cmd1), file=sys.stderr)
            e1 = subprocess.Popen(cmd1, stdout=subprocess.PIPE, stderr=subprocess.PIPE)
            if opt.debug:
                print("# ", e1.stderr, file=sys.stderr)
            subprocess.Popen(["gzip", "-c"], stdin=e1.stdout, stderr=subprocess.PIPE, stdout=output).communicate()
        except Exception as e:
            print("Error:", e, file=sys.stderr)
            return False
    else:
        try:
            if opt.debug:
                print("[cmd] Running: %s" % ' '.join(cmd1), file=sys.stderr)
            subprocess.Popen(cmd1, stderr=subprocess.PIPE, stdout=output).communicate()
        except Exception as e:
            print("Error:", e, file=sys.stderr)
            return False
    return True

def last_seq(file):
    cmd = ["seqfu", "tail", "-n", "1", file]
    p = subprocess.Popen(cmd, stdout=subprocess.PIPE, stderr=subprocess.PIPE)
    return p.stdout.read().decode("utf-8").split("\n")[0].split("\t")[0].split(" ")[0].strip()[1:]

def splitFileBySeqs(input, num_seqs, opt):
    """
    Split a file into multiple files by number of sequences.
    """
    finished = False
    fromArg = None
    fromSeq = None
    n = 0
    while not finished:

        n += 1
        output = open(opt.prefix + str(n).zfill(opt.num_len) + opt.suffix, "w")
        cat = ["seqfu", "cat", opt.format, fromArg, fromSeq, input]
        head = ["seqfu", "head", "-n", str(num_seqs)]
        run  = runcmds(cat, head, output, opt)
        
        last = last_seq(output.name)
       
        if opt.verbose:
            print("Step: ", n, " to: ", output.name, " (last: "+last+")" if last else '(end)', file=sys.stderr)
        
        if last != "":
            fromArg = "--jump-to"
            fromSeq = last
        else:
            # Remove output.name
            output.close()
            delFile(output.name, opt.debug)
            finished = True
        
def splitFileByBp(input, bp, opt):
    """
    Split a file into multiple files by number of sequences.
    """
    finished = False
    fromArg = None
    fromSeq = None
    n = 0
    while not finished:
        n += 1

        output = open(opt.prefix + str(n).zfill(opt.num_len) + opt.suffix, "w")
        if opt.verbose:
            print("Step: ", n, " to: ", output.name, " (last: "+fromSeq+")" if fromSeq else '', file=sys.stderr)
  
        cat = ["seqfu", "cat", opt.format, fromArg, fromSeq, "--max-bp", str(bp), input]
        run  = runSingleCommand(cat, output, opt)
        
        last = last_seq(output.name)      
        if last != "":
            fromArg = "--jump-to"
            fromSeq = last
        else:
            # Remove output.name
            output.close()
            # if empty: remove file
            
            delFile(output.name, opt.debug)
            finished = True

def splitFileInN(input, n, opt):
    """
    Split a file into multiple files evenly distributed using
    multiple threads.
    """
    processes = set()
    for i in range(n):
        cmd = ["seqfu", "cat", "--skip", str(n), "--skip-first", str(i), opt.format, input]
        cmd = removeNone(cmd)
        
        output = open(opt.getOutput(i), "w")
        processes.add(subprocess.Popen(cmd, stdout=output, stderr=subprocess.PIPE))
        if opt.verbose:
            print("Chunk: ", i + 1, " to: ", output.name, file=sys.stderr)
        if len(processes) >= opt.threads:
            os.wait()
            processes.difference_update([
                p for p in processes if p.poll() is not None])
        
        # Wait for all processes to finish
        for p in processes:
            if opt.debug:
                print("Waiting for: ", p.pid, file=sys.stderr)
            p.wait()
            if p.returncode != 0:
                print("Error:", p.stderr.read().decode("utf-8"), file=sys.stderr)
                return False


if __name__ == "__main__":
    import argparse
    parser = argparse.ArgumentParser(description="Split FASTA/FASTQ files into multiple files")
    parser.add_argument("-i", "--input", help="Input file", required=True)
    parser.add_argument("-o", "--output", help="Output file (add a stretch of 3+ zeroes to specify the progressive number), compression will be detected. Example: parz_0000.fq.gz", required=True)

    method = parser.add_mutually_exclusive_group(required=True)
    method.add_argument("-n", "--num-files", help="Number of desired files", type=int)
    method.add_argument("-s", "--num-seqs", help="Number of sequences per file", type=int)
    method.add_argument("-b", "--num-bases", help="Number of bases per file", type=str)

    other = parser.add_argument_group("Other options")
    other.add_argument("--threads", help="Number of threads (-n only) [default: %(default)s", default=8, type=int)
    other.add_argument("--number-char", help="Character used to represent the progressive number in output string [default: %(default)s", default="0", type=str)
    other.add_argument("--compress", help="Force compression of the output files", action="store_true")
    other.add_argument("--verbose", help="Verbose mode", action="store_true")
    other.add_argument("--debug", help="Debug mode", action="store_true")

    # version
    parser.add_argument("--version", action="version", version="%(prog)s " + __VERSION__)
    args = parser.parse_args()

    if not checkSeqfuVersion("1.13.0", args.verbose):
        print("Error: seqfu version 1.13.0 or higher is required.", file=sys.stderr)
        sys.exit(1)

    opt = SplitOpt(args)

    if opt.verbose:
        print(opt, file=sys.stderr)

    if args.num_files is not None:
        splitFileInN(args.input, args.num_files, opt)
    elif args.num_seqs is not None:
        splitFileBySeqs(opt.input, args.num_seqs, opt)
    elif args.num_bases is not None:
        bases = parse_bases(args.num_bases)
        splitFileByBp(opt.input, bases, opt)