# Known adapter sequences adapted from fastp's src/knownadapters.h.
# Source: https://github.com/OpenGene/fastp
# Snapshot: commit 6327c3848cd22034ba1fecd62c069335c7cf8472
# The fastp header notes that some entries came from Stephen Turner's
# adapters_combined_256_unique.fasta collection.
#
# Copyright (c) 2016 OpenGene - Open Source Genetics Toolbox
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.

type KnownAdapter* = object
  sequence*: string
  description*: string

const KNOWN_ADAPTERS* = [
  KnownAdapter(sequence: "AGATCGGAAGAGCACACGTCTGAACTCCAGTCA", description: ">Illumina TruSeq Adapter Read 1"),
  KnownAdapter(sequence: "AGATCGGAAGAGCGTCGTGTAGGGAAAGAGTGT", description: ">Illumina TruSeq Adapter Read 2"),
  KnownAdapter(sequence: "GATCGTCGGACTGTAGAACTCTGAACGTGTAGA", description: ">Illumina Small RNA Adapter Read 2"),
  KnownAdapter(sequence: "AATGATACGGCGACCACCGACAGGTTCAGAGTTCTACAGTCCGA", description: ">Illumina DpnII expression PCR Primer 2 | >Illumina NlaIII expression PCR Primer 2 | >Illumina Small RNA PCR Primer 2 | >Illumina DpnII Gex PCR Primer 2 | >Illumina NlaIII Gex PCR Primer 2"),
  KnownAdapter(sequence: "AATGATACGGCGACCACCGAGATCTACACGTTCAGAGTTCTACAGTCCGA", description: ">Illumina RNA PCR Primer"),
  KnownAdapter(sequence: "AATGATACGGCGACCACCGAGATCTACACTCTTTCCCTACACGACGCTCTTCCGATCT", description: ">TruSeq_Universal_Adapter | >PrefixPE/1 | >PCR_Primer1 | >Illumina Single End PCR Primer 1 | >Illumina Paried End PCR Primer 1 | >Illumina Multiplexing PCR Primer 1.01 | >TruSeq Universal Adapter | >TruSeq_Universal_Adapter | >PrefixPE/1 | >PCR_Primer1"),
  KnownAdapter(sequence: "AATGATACGGCGACCACCGAGATCTACACTCTTTCCCTACACGACGCTCTTCCGATCTAGATCGGAAGAGCGGTTCAGCAGGAATGCCGAGACCGATCTCGTATGCCGTCTTCTGCTTG", description: ">pcr_dimer"),
  KnownAdapter(sequence: "AATGATACGGCGACCACCGAGATCTACACTCTTTCCCTACACGACGCTCTTCCGATCTCAAGCAGAAGACGGCATACGAGCTCTTCCGATCT", description: ">PCR_Primers"),
  KnownAdapter(sequence: "ACACTCTTTCCCTACACGACGCTCTTCCGATCT", description: ">Illumina Single End Sequencing Primer | >Illumina Paired End Adapter 1 | >Illumina Paried End Sequencing Primer 1 | >Illumina Multiplexing Adapter 2 | >Illumina Multiplexing Read1 Sequencing Primer"),
  KnownAdapter(sequence: "AGATCGGAAGAGCACACGTCTGAACTCCAGTCAC", description: ">PE2_rc | >TruSeq3_IndexedAdapter | >PE2_rc | >TruSeq3_IndexedAdapter"),
  KnownAdapter(sequence: "AGATCGGAAGAGCACACGTCTGAACTCCAGTCACATCACGATCTCGTATGCCGTCTTCTGCTTG", description: ">Reverse_adapter"),
  KnownAdapter(sequence: "AGATCGGAAGAGCGGTTCAGCAGGAATGCCGAG", description: ">TruSeq2_PE_r"),
  KnownAdapter(sequence: "AGATCGGAAGAGCGGTTCAGCAGGAATGCCGAGACCGATCTCGTATGCCGTCTTCTGCTTG", description: ">PCR_Primer2_rc"),
  KnownAdapter(sequence: "AGATCGGAAGAGCGGTTCAGCAGGAATGCCGAGACCGATCTCGTATGCCGTCTTCTGCTTGAAA", description: ">PhiX_read1_adapter"),
  KnownAdapter(sequence: "AGATCGGAAGAGCGTCGTGTAGGGAAAGAGTGTA", description: ">PE1_rc | >TruSeq3_UniversalAdapter | >PE1_rc | >TruSeq3_UniversalAdapter"),
  KnownAdapter(sequence: "AGATCGGAAGAGCGTCGTGTAGGGAAAGAGTGTAGATCTCGGTGGTCGCCGTATCATT", description: ">PCR_Primer1_rc"),
  KnownAdapter(sequence: "AGATCGGAAGAGCGTCGTGTAGGGAAAGAGTGTAGATCTCGGTGGTCGCCGTATCATTAAAAAA", description: ">PhiX_read2_adapter"),
  KnownAdapter(sequence: "AGATCGGAAGAGCTCGTATGCCGTCTTCTGCTTG", description: ">TruSeq2_SE"),
  KnownAdapter(sequence: "CAAGCAGAAGACGGCATACGAGATAAAATGGTGACTGGAGTTCCTTGGCACCCGAGAATTCCA", description: ">RNA PCR Primer, Index 35"),
  KnownAdapter(sequence: "CAAGCAGAAGACGGCATACGAGATAAGCTAGTGACTGGAGTTC", description: ">Illumina PCR Primer Index 10"),
  KnownAdapter(sequence: "CAAGCAGAAGACGGCATACGAGATAAGCTAGTGACTGGAGTTCCTTGGCACCCGAGAATTCCA", description: ">RNA PCR Primer, Index 10"),
  KnownAdapter(sequence: "CAAGCAGAAGACGGCATACGAGATACATCGGTGACTGGAGTTC", description: ">Illumina PCR Primer Index 2"),
  KnownAdapter(sequence: "CAAGCAGAAGACGGCATACGAGATACATCGGTGACTGGAGTTCCTTGGCACCCGAGAATTCCA", description: ">RNA PCR Primer, Index 2"),
  KnownAdapter(sequence: "CAAGCAGAAGACGGCATACGAGATAGCTAGGTGACTGGAGTTCCTTGGCACCCGAGAATTCCA", description: ">RNA PCR Primer, Index 38"),
  KnownAdapter(sequence: "CAAGCAGAAGACGGCATACGAGATAGGAATGTGACTGGAGTTCCTTGGCACCCGAGAATTCCA", description: ">RNA PCR Primer, Index 27"),
  KnownAdapter(sequence: "CAAGCAGAAGACGGCATACGAGATATCAGTGTGACTGGAGTTCCTTGGCACCCGAGAATTCCA", description: ">RNA PCR Primer, Index 25"),
  KnownAdapter(sequence: "CAAGCAGAAGACGGCATACGAGATATCGTGGTGACTGGAGTTCCTTGGCACCCGAGAATTCCA", description: ">RNA PCR Primer, Index 31"),
  KnownAdapter(sequence: "CAAGCAGAAGACGGCATACGAGATATTATAGTGACTGGAGTTCCTTGGCACCCGAGAATTCCA", description: ">RNA PCR Primer, Index 44"),
  KnownAdapter(sequence: "CAAGCAGAAGACGGCATACGAGATATTCCGGTGACTGGAGTTCCTTGGCACCCGAGAATTCCA", description: ">RNA PCR Primer, Index 37"),
  KnownAdapter(sequence: "CAAGCAGAAGACGGCATACGAGATATTGGCGTGACTGGAGTTC", description: ">Illumina PCR Primer Index 6"),
  KnownAdapter(sequence: "CAAGCAGAAGACGGCATACGAGATATTGGCGTGACTGGAGTTCCTTGGCACCCGAGAATTCCA", description: ">RNA PCR Primer, Index 6"),
  KnownAdapter(sequence: "CAAGCAGAAGACGGCATACGAGATCACTGTGTGACTGGAGTTC", description: ">Illumina PCR Primer Index 5"),
  KnownAdapter(sequence: "CAAGCAGAAGACGGCATACGAGATCACTGTGTGACTGGAGTTCCTTGGCACCCGAGAATTCCA", description: ">RNA PCR Primer, Index 5"),
  KnownAdapter(sequence: "CAAGCAGAAGACGGCATACGAGATCCACTCGTGACTGGAGTTCCTTGGCACCCGAGAATTCCA", description: ">RNA PCR Primer, Index 23"),
  KnownAdapter(sequence: "CAAGCAGAAGACGGCATACGAGATCCGGTGGTGACTGGAGTTCCTTGGCACCCGAGAATTCCA", description: ">RNA PCR Primer, Index 30"),
  KnownAdapter(sequence: "CAAGCAGAAGACGGCATACGAGATCGAAACGTGACTGGAGTTCCTTGGCACCCGAGAATTCCA", description: ">RNA PCR Primer, Index 21"),
  KnownAdapter(sequence: "CAAGCAGAAGACGGCATACGAGATCGATTAGTGACTGGAGTTCCTTGGCACCCGAGAATTCCA", description: ">RNA PCR Primer, Index 42"),
  KnownAdapter(sequence: "CAAGCAGAAGACGGCATACGAGATCGCCTGGTGACTGGAGTTCCTTGGCACCCGAGAATTCCA", description: ">RNA PCR Primer, Index 33"),
  KnownAdapter(sequence: "CAAGCAGAAGACGGCATACGAGATCGGTCTCGGCATTCCTGCTGAACCGCTCTTCCGATCT", description: ">PrefixPE/2 | >PCR_Primer2 | >Illumina Paired End PCR Primer 2 | >PrefixPE/2 | >PCR_Primer2"),
  KnownAdapter(sequence: "CAAGCAGAAGACGGCATACGAGATCGTACGGTGACTGGAGTTCCTTGGCACCCGAGAATTCCA", description: ">RNA PCR Primer, Index 22"),
  KnownAdapter(sequence: "CAAGCAGAAGACGGCATACGAGATCGTGATGTGACTGGAGTTC", description: ">Illumina PCR Primer Index 1"),
  KnownAdapter(sequence: "CAAGCAGAAGACGGCATACGAGATCGTGATGTGACTGGAGTTCCTTGGCACCCGAGAATTCCA", description: ">RNA PCR Primer, Index 1"),
  KnownAdapter(sequence: "CAAGCAGAAGACGGCATACGAGATCTCTACGTGACTGGAGTTCCTTGGCACCCGAGAATTCCA", description: ">RNA PCR Primer, Index 17"),
  KnownAdapter(sequence: "CAAGCAGAAGACGGCATACGAGATCTGATCGTGACTGGAGTTC", description: ">Illumina PCR Primer Index 9"),
  KnownAdapter(sequence: "CAAGCAGAAGACGGCATACGAGATCTGATCGTGACTGGAGTTCCTTGGCACCCGAGAATTCCA", description: ">RNA PCR Primer, Index 9"),
  KnownAdapter(sequence: "CAAGCAGAAGACGGCATACGAGATCTTCGAGTGACTGGAGTTCCTTGGCACCCGAGAATTCCA", description: ">RNA PCR Primer, Index 47"),
  KnownAdapter(sequence: "CAAGCAGAAGACGGCATACGAGATCTTTTGGTGACTGGAGTTCCTTGGCACCCGAGAATTCCA", description: ">RNA PCR Primer, Index 28"),
  KnownAdapter(sequence: "CAAGCAGAAGACGGCATACGAGATGAATGAGTGACTGGAGTTCCTTGGCACCCGAGAATTCCA", description: ">RNA PCR Primer, Index 45"),
  KnownAdapter(sequence: "CAAGCAGAAGACGGCATACGAGATGATCTGGTGACTGGAGTTC", description: ">Illumina PCR Primer Index 7"),
  KnownAdapter(sequence: "CAAGCAGAAGACGGCATACGAGATGATCTGGTGACTGGAGTTCCTTGGCACCCGAGAATTCCA", description: ">RNA PCR Primer, Index 7"),
  KnownAdapter(sequence: "CAAGCAGAAGACGGCATACGAGATGCCATGGTGACTGGAGTTCCTTGGCACCCGAGAATTCCA", description: ">RNA PCR Primer, Index 34"),
  KnownAdapter(sequence: "CAAGCAGAAGACGGCATACGAGATGCCTAAGTGACTGGAGTTC", description: ">Illumina PCR Primer Index 3"),
  KnownAdapter(sequence: "CAAGCAGAAGACGGCATACGAGATGCCTAAGTGACTGGAGTTCCTTGGCACCCGAGAATTCCA", description: ">RNA PCR Primer, Index 3"),
  KnownAdapter(sequence: "CAAGCAGAAGACGGCATACGAGATGCGGACGTGACTGGAGTTCCTTGGCACCCGAGAATTCCA", description: ">RNA PCR Primer, Index 18"),
  KnownAdapter(sequence: "CAAGCAGAAGACGGCATACGAGATGCTACCGTGACTGGAGTTCCTTGGCACCCGAGAATTCCA", description: ">RNA PCR Primer, Index 24"),
  KnownAdapter(sequence: "CAAGCAGAAGACGGCATACGAGATGCTCATGTGACTGGAGTTCCTTGGCACCCGAGAATTCCA", description: ">RNA PCR Primer, Index 26"),
  KnownAdapter(sequence: "CAAGCAGAAGACGGCATACGAGATGCTGTAGTGACTGGAGTTCCTTGGCACCCGAGAATTCCA", description: ">RNA PCR Primer, Index 43"),
  KnownAdapter(sequence: "CAAGCAGAAGACGGCATACGAGATGGAACTGTGACTGGAGTTCCTTGGCACCCGAGAATTCCA", description: ">RNA PCR Primer, Index 14"),
  KnownAdapter(sequence: "CAAGCAGAAGACGGCATACGAGATGGACGGGTGACTGGAGTTCCTTGGCACCCGAGAATTCCA", description: ">RNA PCR Primer, Index 16"),
  KnownAdapter(sequence: "CAAGCAGAAGACGGCATACGAGATGGCCACGTGACTGGAGTTCCTTGGCACCCGAGAATTCCA", description: ">RNA PCR Primer, Index 20"),
  KnownAdapter(sequence: "CAAGCAGAAGACGGCATACGAGATGTAGCCGTGACTGGAGTTC", description: ">Illumina PCR Primer Index 11"),
  KnownAdapter(sequence: "CAAGCAGAAGACGGCATACGAGATGTAGCCGTGACTGGAGTTCCTTGGCACCCGAGAATTCCA", description: ">RNA PCR Primer, Index 11"),
  KnownAdapter(sequence: "CAAGCAGAAGACGGCATACGAGATGTATAGGTGACTGGAGTTCCTTGGCACCCGAGAATTCCA", description: ">RNA PCR Primer, Index 39"),
  KnownAdapter(sequence: "CAAGCAGAAGACGGCATACGAGATGTCGTCGTGACTGGAGTTCCTTGGCACCCGAGAATTCCA", description: ">RNA PCR Primer, Index 41"),
  KnownAdapter(sequence: "CAAGCAGAAGACGGCATACGAGATTACAAGGTGACTGGAGTTC", description: ">Illumina PCR Primer Index 12"),
  KnownAdapter(sequence: "CAAGCAGAAGACGGCATACGAGATTACAAGGTGACTGGAGTTCCTTGGCACCCGAGAATTCCA", description: ">RNA PCR Primer, Index 12"),
  KnownAdapter(sequence: "CAAGCAGAAGACGGCATACGAGATTAGTTGGTGACTGGAGTTCCTTGGCACCCGAGAATTCCA", description: ">RNA PCR Primer, Index 29"),
  KnownAdapter(sequence: "CAAGCAGAAGACGGCATACGAGATTCAAGTGTGACTGGAGTTC", description: ">Illumina PCR Primer Index 8"),
  KnownAdapter(sequence: "CAAGCAGAAGACGGCATACGAGATTCAAGTGTGACTGGAGTTCCTTGGCACCCGAGAATTCCA", description: ">RNA PCR Primer, Index 8"),
  KnownAdapter(sequence: "CAAGCAGAAGACGGCATACGAGATTCGGGAGTGACTGGAGTTCCTTGGCACCCGAGAATTCCA", description: ">RNA PCR Primer, Index 46"),
  KnownAdapter(sequence: "CAAGCAGAAGACGGCATACGAGATTCTGAGGTGACTGGAGTTCCTTGGCACCCGAGAATTCCA", description: ">RNA PCR Primer, Index 40"),
  KnownAdapter(sequence: "CAAGCAGAAGACGGCATACGAGATTGACATGTGACTGGAGTTCCTTGGCACCCGAGAATTCCA", description: ">RNA PCR Primer, Index 15"),
  KnownAdapter(sequence: "CAAGCAGAAGACGGCATACGAGATTGAGTGGTGACTGGAGTTCCTTGGCACCCGAGAATTCCA", description: ">RNA PCR Primer, Index 32"),
  KnownAdapter(sequence: "CAAGCAGAAGACGGCATACGAGATTGCCGAGTGACTGGAGTTCCTTGGCACCCGAGAATTCCA", description: ">RNA PCR Primer, Index 48"),
  KnownAdapter(sequence: "CAAGCAGAAGACGGCATACGAGATTGGTCAGTGACTGGAGTTC", description: ">Illumina PCR Primer Index 4"),
  KnownAdapter(sequence: "CAAGCAGAAGACGGCATACGAGATTGGTCAGTGACTGGAGTTCCTTGGCACCCGAGAATTCCA", description: ">RNA PCR Primer, Index 4"),
  KnownAdapter(sequence: "CAAGCAGAAGACGGCATACGAGATTGTTGGGTGACTGGAGTTCCTTGGCACCCGAGAATTCCA", description: ">RNA PCR Primer, Index 36"),
  KnownAdapter(sequence: "CAAGCAGAAGACGGCATACGAGATTTGACTGTGACTGGAGTTCCTTGGCACCCGAGAATTCCA", description: ">RNA PCR Primer, Index 13"),
  KnownAdapter(sequence: "CAAGCAGAAGACGGCATACGAGATTTTCACGTGACTGGAGTTCCTTGGCACCCGAGAATTCCA", description: ">RNA PCR Primer, Index 19"),
  KnownAdapter(sequence: "CAAGCAGAAGACGGCATACGAGCTCTTCCGATCT", description: ">Illumina Single End Adapter 2 | >Illumina Single End PCR Primer 2"),
  KnownAdapter(sequence: "CCACTACGCCTCCGCTTTCCTCTCTATGGGCAGTCGGTGAT", description: ">ABI Solid3 Adapter B"),
  KnownAdapter(sequence: "CCGACAGGTTCAGAGTTCTACAGTCCGACATG", description: ">Illumina NlaIII expression Sequencing Primer | >Illumina NlaIII Gex Sequencing Primer"),
  KnownAdapter(sequence: "CCGAGCCCACGAGACAAGAGGCAATCTCGTATGCCGTCTTCTGCTTG", description: ">I7_Primer_Nextera_XT_and_Nextera_Enrichment_N711 | >I7_Primer_Nextera_XT_Index_Kit_v2_N711 | >I7_Primer_Nextera_XT_and_Nextera_Enrichment_N711 | >I7_Primer_Nextera_XT_Index_Kit_v2_N711"),
  KnownAdapter(sequence: "CCGAGCCCACGAGACACTCGCTAATCTCGTATGCCGTCTTCTGCTTG", description: ">I7_Primer_Nextera_XT_Index_Kit_v2_N716"),
  KnownAdapter(sequence: "CCGAGCCCACGAGACACTGAGCGATCTCGTATGCCGTCTTCTGCTTG", description: ">I7_Primer_Nextera_XT_Index_Kit_v2_N724"),
  KnownAdapter(sequence: "CCGAGCCCACGAGACAGGCAGAAATCTCGTATGCCGTCTTCTGCTTG", description: ">I7_Primer_Nextera_XT_and_Nextera_Enrichment_N703 | >I7_Primer_Nextera_XT_Index_Kit_v2_N703 | >I7_Primer_Nextera_XT_and_Nextera_Enrichment_N703 | >I7_Primer_Nextera_XT_Index_Kit_v2_N703"),
  KnownAdapter(sequence: "CCGAGCCCACGAGACATCTCAGGATCTCGTATGCCGTCTTCTGCTTG", description: ">I7_Primer_Nextera_XT_Index_Kit_v2_N715"),
  KnownAdapter(sequence: "CCGAGCCCACGAGACATGCGCAGATCTCGTATGCCGTCTTCTGCTTG", description: ">I7_Primer_Nextera_XT_Index_Kit_v2_N722"),
  KnownAdapter(sequence: "CCGAGCCCACGAGACCAGAGAGGATCTCGTATGCCGTCTTCTGCTTG", description: ">I7_Primer_Nextera_XT_and_Nextera_Enrichment_N708"),
  KnownAdapter(sequence: "CCGAGCCCACGAGACCCTAAGACATCTCGTATGCCGTCTTCTGCTTG", description: ">I7_Primer_Nextera_XT_Index_Kit_v2_N726"),
  KnownAdapter(sequence: "CCGAGCCCACGAGACCGAGGCTGATCTCGTATGCCGTCTTCTGCTTG", description: ">I7_Primer_Nextera_XT_and_Nextera_Enrichment_N710 | >I7_Primer_Nextera_XT_Index_Kit_v2_N710 | >I7_Primer_Nextera_XT_and_Nextera_Enrichment_N710 | >I7_Primer_Nextera_XT_Index_Kit_v2_N710"),
  KnownAdapter(sequence: "CCGAGCCCACGAGACCGATCAGTATCTCGTATGCCGTCTTCTGCTTG", description: ">I7_Primer_Nextera_XT_Index_Kit_v2_N727"),
  KnownAdapter(sequence: "CCGAGCCCACGAGACCGGAGCCTATCTCGTATGCCGTCTTCTGCTTG", description: ">I7_Primer_Nextera_XT_Index_Kit_v2_N720"),
  KnownAdapter(sequence: "CCGAGCCCACGAGACCGTACTAGATCTCGTATGCCGTCTTCTGCTTG", description: ">I7_Primer_Nextera_XT_and_Nextera_Enrichment_N702 | >I7_Primer_Nextera_XT_Index_Kit_v2_N702 | >I7_Primer_Nextera_XT_and_Nextera_Enrichment_N702 | >I7_Primer_Nextera_XT_Index_Kit_v2_N702"),
  KnownAdapter(sequence: "CCGAGCCCACGAGACCTCTCTACATCTCGTATGCCGTCTTCTGCTTG", description: ">I7_Primer_Nextera_XT_and_Nextera_Enrichment_N707 | >I7_Primer_Nextera_XT_Index_Kit_v2_N707 | >I7_Primer_Nextera_XT_and_Nextera_Enrichment_N707 | >I7_Primer_Nextera_XT_Index_Kit_v2_N707"),
  KnownAdapter(sequence: "CCGAGCCCACGAGACGCGTAGTAATCTCGTATGCCGTCTTCTGCTTG", description: ">I7_Primer_Nextera_XT_Index_Kit_v2_N719"),
  KnownAdapter(sequence: "CCGAGCCCACGAGACGCTACGCTATCTCGTATGCCGTCTTCTGCTTG", description: ">I7_Primer_Nextera_XT_and_Nextera_Enrichment_N709"),
  KnownAdapter(sequence: "CCGAGCCCACGAGACGCTCATGAATCTCGTATGCCGTCTTCTGCTTG", description: ">I7_Primer_Nextera_XT_Index_Kit_v2_N714"),
  KnownAdapter(sequence: "CCGAGCCCACGAGACGGACTCCTATCTCGTATGCCGTCTTCTGCTTG", description: ">I7_Primer_Nextera_XT_and_Nextera_Enrichment_N705 | >I7_Primer_Nextera_XT_Index_Kit_v2_N705 | >I7_Primer_Nextera_XT_and_Nextera_Enrichment_N705 | >I7_Primer_Nextera_XT_Index_Kit_v2_N705"),
  KnownAdapter(sequence: "CCGAGCCCACGAGACGGAGCTACATCTCGTATGCCGTCTTCTGCTTG", description: ">I7_Primer_Nextera_XT_Index_Kit_v2_N718"),
  KnownAdapter(sequence: "CCGAGCCCACGAGACGTAGAGGAATCTCGTATGCCGTCTTCTGCTTG", description: ">I7_Primer_Nextera_XT_and_Nextera_Enrichment_N712 | >I7_Primer_Nextera_XT_Index_Kit_v2_N712 | >I7_Primer_Nextera_XT_and_Nextera_Enrichment_N712 | >I7_Primer_Nextera_XT_Index_Kit_v2_N712"),
  KnownAdapter(sequence: "CCGAGCCCACGAGACTAAGGCGAATCTCGTATGCCGTCTTCTGCTTG", description: ">I7_Primer_Nextera_XT_and_Nextera_Enrichment_N701 | >I7_Primer_Nextera_XT_Index_Kit_v2_N701 | >I7_Primer_Nextera_XT_and_Nextera_Enrichment_N701 | >I7_Primer_Nextera_XT_Index_Kit_v2_N701"),
  KnownAdapter(sequence: "CCGAGCCCACGAGACTACGCTGCATCTCGTATGCCGTCTTCTGCTTG", description: ">I7_Primer_Nextera_XT_Index_Kit_v2_N721"),
  KnownAdapter(sequence: "CCGAGCCCACGAGACTAGCGCTCATCTCGTATGCCGTCTTCTGCTTG", description: ">I7_Primer_Nextera_XT_Index_Kit_v2_N723"),
  KnownAdapter(sequence: "CCGAGCCCACGAGACTAGGCATGATCTCGTATGCCGTCTTCTGCTTG", description: ">I7_Primer_Nextera_XT_and_Nextera_Enrichment_N706 | >I7_Primer_Nextera_XT_Index_Kit_v2_N706 | >I7_Primer_Nextera_XT_and_Nextera_Enrichment_N706 | >I7_Primer_Nextera_XT_Index_Kit_v2_N706"),
  KnownAdapter(sequence: "CCGAGCCCACGAGACTCCTGAGCATCTCGTATGCCGTCTTCTGCTTG", description: ">I7_Primer_Nextera_XT_and_Nextera_Enrichment_N704 | >I7_Primer_Nextera_XT_Index_Kit_v2_N704 | >I7_Primer_Nextera_XT_and_Nextera_Enrichment_N704 | >I7_Primer_Nextera_XT_Index_Kit_v2_N704"),
  KnownAdapter(sequence: "CCGAGCCCACGAGACTCGACGTCATCTCGTATGCCGTCTTCTGCTTG", description: ">I7_Primer_Nextera_XT_Index_Kit_v2_N729"),
  KnownAdapter(sequence: "CCGAGCCCACGAGACTGCAGCTAATCTCGTATGCCGTCTTCTGCTTG", description: ">I7_Primer_Nextera_XT_Index_Kit_v2_N728"),
  KnownAdapter(sequence: "CGACAGGTTCAGAGTTCTACAGTCCGACGATC", description: ">Illumina DpnII expression Sequencing Primer | >Illumina Small RNA Sequencing Primer | >Illumina DpnII Gex Sequencing Primer"),
  KnownAdapter(sequence: "CGGTCTCGGCATTCCTGCTGAACCGCTCTTCCGATCT", description: ">Illumina Paired End Sequencing Primer 2"),
  KnownAdapter(sequence: "CTAATACGACTCACTATAGGGCAAGCAGTGGTATCAACGCAGAGT", description: ">Clontech Universal Primer Mix Long"),
  KnownAdapter(sequence: "CTGAGCGGGCTGGCAAGGCAGACCGATCTCGTATGCCGTCTTCTGCTTG", description: ">I7_Adapter_Nextera_No_Barcode"),
  KnownAdapter(sequence: "CTGATGGCGCGAGGGAGGCGTGTAGATCTCGGTGGTCGCCGTATCATT", description: ">I5_Adapter_Nextera"),
  KnownAdapter(sequence: "CTGCCCCGGGTTCCTCATTCTCTCAGCAGCATG", description: ">ABI Solid3 Adapter A"),
  KnownAdapter(sequence: "CTGTCTCTTATACACATCTCCGAGCCCACGAGAC", description: ">I7_Nextera_Transposase_1 | >Trans2_rc | >I7_Nextera_Transposase_1 | >Trans2_rc"),
  KnownAdapter(sequence: "CTGTCTCTTATACACATCTCTGAGCGGGCTGGCAAGGC", description: ">I7_Nextera_Transposase_2"),
  KnownAdapter(sequence: "CTGTCTCTTATACACATCTCTGATGGCGCGAGGGAGGC", description: ">I5_Nextera_Transposase_2"),
  KnownAdapter(sequence: "CTGTCTCTTATACACATCTGACGCTGCCGACGA", description: ">I5_Nextera_Transposase_1 | >Trans1_rc | >I5_Nextera_Transposase_1 | >Trans1_rc"),
  KnownAdapter(sequence: "GACGCTGCCGACGAACTCTAGGGTGTAGATCTCGGTGGTCGCCGTATCATT", description: ">I5_Primer_Nextera_XT_Index_Kit_v2_S516"),
  KnownAdapter(sequence: "GACGCTGCCGACGAAGAGGATAGTGTAGATCTCGGTGGTCGCCGTATCATT", description: ">I5_Primer_Nextera_XT_and_Nextera_Enrichment_[N/S/E]503 | >I5_Primer_Nextera_XT_Index_Kit_v2_S503 | >I5_Primer_Nextera_XT_and_Nextera_Enrichment_[N/S/E]503 | >I5_Primer_Nextera_XT_Index_Kit_v2_S503"),
  KnownAdapter(sequence: "GACGCTGCCGACGAAGCTAGAAGTGTAGATCTCGGTGGTCGCCGTATCATT", description: ">I5_Primer_Nextera_XT_Index_Kit_v2_S515"),
  KnownAdapter(sequence: "GACGCTGCCGACGAAGGCTTAGGTGTAGATCTCGGTGGTCGCCGTATCATT", description: ">I5_Primer_Nextera_XT_and_Nextera_Enrichment_[N/S/E]508 | >I5_Primer_Nextera_XT_Index_Kit_v2_S508 | >I5_Primer_Nextera_XT_and_Nextera_Enrichment_[N/S/E]508 | >I5_Primer_Nextera_XT_Index_Kit_v2_S508"),
  KnownAdapter(sequence: "GACGCTGCCGACGAATAGAGAGGTGTAGATCTCGGTGGTCGCCGTATCATT", description: ">I5_Primer_Nextera_XT_and_Nextera_Enrichment_[N/S/E]502 | >I5_Primer_Nextera_XT_Index_Kit_v2_S502 | >I5_Primer_Nextera_XT_and_Nextera_Enrichment_[N/S/E]502 | >I5_Primer_Nextera_XT_Index_Kit_v2_S502"),
  KnownAdapter(sequence: "GACGCTGCCGACGAATAGCCTTGTGTAGATCTCGGTGGTCGCCGTATCATT", description: ">I5_Primer_Nextera_XT_Index_Kit_v2_S520"),
  KnownAdapter(sequence: "GACGCTGCCGACGAATTAGACGGTGTAGATCTCGGTGGTCGCCGTATCATT", description: ">I5_Primer_Nextera_XT_Index_Kit_v2_S510"),
  KnownAdapter(sequence: "GACGCTGCCGACGACGGAGAGAGTGTAGATCTCGGTGGTCGCCGTATCATT", description: ">I5_Primer_Nextera_XT_Index_Kit_v2_S511"),
  KnownAdapter(sequence: "GACGCTGCCGACGACTAGTCGAGTGTAGATCTCGGTGGTCGCCGTATCATT", description: ">I5_Primer_Nextera_XT_Index_Kit_v2_S513"),
  KnownAdapter(sequence: "GACGCTGCCGACGACTCCTTACGTGTAGATCTCGGTGGTCGCCGTATCATT", description: ">I5_Primer_Nextera_XT_and_Nextera_Enrichment_[N/S/E]505 | >I5_Primer_Nextera_XT_Index_Kit_v2_S505 | >I5_Primer_Nextera_XT_and_Nextera_Enrichment_[N/S/E]505 | >I5_Primer_Nextera_XT_Index_Kit_v2_S505"),
  KnownAdapter(sequence: "GACGCTGCCGACGACTTAATAGGTGTAGATCTCGGTGGTCGCCGTATCATT", description: ">I5_Primer_Nextera_XT_Index_Kit_v2_S518"),
  KnownAdapter(sequence: "GACGCTGCCGACGAGCGATCTAGTGTAGATCTCGGTGGTCGCCGTATCATT", description: ">I5_Primer_Nextera_XT_and_Nextera_Enrichment_[N/S/E]501"),
  KnownAdapter(sequence: "GACGCTGCCGACGATAAGGCTCGTGTAGATCTCGGTGGTCGCCGTATCATT", description: ">I5_Primer_Nextera_XT_Index_Kit_v2_S521"),
  KnownAdapter(sequence: "GACGCTGCCGACGATACTCCTTGTGTAGATCTCGGTGGTCGCCGTATCATT", description: ">I5_Primer_Nextera_XT_and_Nextera_Enrichment_[N/S/E]507 | >I5_Primer_Nextera_XT_Index_Kit_v2_S507 | >I5_Primer_Nextera_XT_and_Nextera_Enrichment_[N/S/E]507 | >I5_Primer_Nextera_XT_Index_Kit_v2_S507"),
  KnownAdapter(sequence: "GACGCTGCCGACGATATGCAGTGTGTAGATCTCGGTGGTCGCCGTATCATT", description: ">I5_Primer_Nextera_XT_and_Nextera_Enrichment_[N/S/E]506 | >I5_Primer_Nextera_XT_Index_Kit_v2_S506 | >I5_Primer_Nextera_XT_and_Nextera_Enrichment_[N/S/E]506 | >I5_Primer_Nextera_XT_Index_Kit_v2_S506"),
  KnownAdapter(sequence: "GACGCTGCCGACGATCGCATAAGTGTAGATCTCGGTGGTCGCCGTATCATT", description: ">I5_Primer_Nextera_XT_Index_Kit_v2_S522"),
  KnownAdapter(sequence: "GACGCTGCCGACGATCTACTCTGTGTAGATCTCGGTGGTCGCCGTATCATT", description: ">I5_Primer_Nextera_XT_and_Nextera_Enrichment_[N/S/E]504"),
  KnownAdapter(sequence: "GACGCTGCCGACGATCTTACGCGTGTAGATCTCGGTGGTCGCCGTATCATT", description: ">I5_Primer_Nextera_XT_and_Nextera_Enrichment_[N/S/E]517 | >I5_Primer_Nextera_XT_Index_Kit_v2_S517 | >I5_Primer_Nextera_XT_and_Nextera_Enrichment_[N/S/E]517 | >I5_Primer_Nextera_XT_Index_Kit_v2_S517"),
  KnownAdapter(sequence: "GATCGGAAGAGCACACGTCTGAACTCCAGTCAC", description: ">Nextera_LMP_Read1_External_Adapter | >Illumina Multiplexing Index Sequencing Primer"),
  KnownAdapter(sequence: "GATCGGAAGAGCACACGTCTGAACTCCAGTCACACAGTGATCTCGTATGCCGTCTTCTGCTTG", description: ">TruSeq_Adapter_Index_5 | >TruSeq Adapter, Index 5"),
  KnownAdapter(sequence: "GATCGGAAGAGCACACGTCTGAACTCCAGTCACACTGATATATCTCGTATGCCGTCTTCTGCTTG", description: ">TruSeq_Adapter_Index_25"),
  KnownAdapter(sequence: "GATCGGAAGAGCACACGTCTGAACTCCAGTCACACTGATATCTCGTATGCCGTCTTCTGCTTG", description: ">TruSeq Adapter, Index 25"),
  KnownAdapter(sequence: "GATCGGAAGAGCACACGTCTGAACTCCAGTCACACTTGAATCTCGTATGCCGTCTTCTGCTTG", description: ">TruSeq_Adapter_Index_8 | >TruSeq Adapter, Index 8"),
  KnownAdapter(sequence: "GATCGGAAGAGCACACGTCTGAACTCCAGTCACAGTCAACAATCTCGTATGCCGTCTTCTGCTTG", description: ">TruSeq_Adapter_Index_13"),
  KnownAdapter(sequence: "GATCGGAAGAGCACACGTCTGAACTCCAGTCACAGTCAACTCTCGTATGCCGTCTTCTGCTTG", description: ">TruSeq Adapter, Index 13"),
  KnownAdapter(sequence: "GATCGGAAGAGCACACGTCTGAACTCCAGTCACAGTTCCGTATCTCGTATGCCGTCTTCTGCTTG", description: ">TruSeq_Adapter_Index_14"),
  KnownAdapter(sequence: "GATCGGAAGAGCACACGTCTGAACTCCAGTCACAGTTCCGTCTCGTATGCCGTCTTCTGCTTG", description: ">TruSeq Adapter, Index 14"),
  KnownAdapter(sequence: "GATCGGAAGAGCACACGTCTGAACTCCAGTCACATCACGATCTCGTATGCCGTCTTCTGCTTG", description: ">TruSeq_Adapter_Index_1_6 | >TruSeq Adapter, Index 1"),
  KnownAdapter(sequence: "GATCGGAAGAGCACACGTCTGAACTCCAGTCACATGTCAGAATCTCGTATGCCGTCTTCTGCTTG", description: ">TruSeq_Adapter_Index_15"),
  KnownAdapter(sequence: "GATCGGAAGAGCACACGTCTGAACTCCAGTCACATGTCAGTCTCGTATGCCGTCTTCTGCTTG", description: ">TruSeq Adapter, Index 15"),
  KnownAdapter(sequence: "GATCGGAAGAGCACACGTCTGAACTCCAGTCACATTCCTTTATCTCGTATGCCGTCTTCTGCTTG", description: ">TruSeq_Adapter_Index_27"),
  KnownAdapter(sequence: "GATCGGAAGAGCACACGTCTGAACTCCAGTCACATTCCTTTCTCGTATGCCGTCTTCTGCTTG", description: ">TruSeq Adapter, Index 27"),
  KnownAdapter(sequence: "GATCGGAAGAGCACACGTCTGAACTCCAGTCACCAGATCATCTCGTATGCCGTCTTCTGCTTG", description: ">TruSeq_Adapter_Index_7 | >TruSeq Adapter, Index 7"),
  KnownAdapter(sequence: "GATCGGAAGAGCACACGTCTGAACTCCAGTCACCCACTCTTCTCGTATGCCGTCTTCTGCTTG", description: ">TruSeq Adapter, Index 23"),
  KnownAdapter(sequence: "GATCGGAAGAGCACACGTCTGAACTCCAGTCACCCGTCCCGATCTCGTATGCCGTCTTCTGCTTG", description: ">TruSeq_Adapter_Index_16"),
  KnownAdapter(sequence: "GATCGGAAGAGCACACGTCTGAACTCCAGTCACCCGTCCCTCTCGTATGCCGTCTTCTGCTTG", description: ">TruSeq Adapter, Index 16"),
  KnownAdapter(sequence: "GATCGGAAGAGCACACGTCTGAACTCCAGTCACCGATGTATCTCGTATGCCGTCTTCTGCTTG", description: ">TruSeq_Adapter_Index_2 | >TruSeq Adapter, Index 2"),
  KnownAdapter(sequence: "GATCGGAAGAGCACACGTCTGAACTCCAGTCACCGTACGTAATCTCGTATGCCGTCTTCTGCTTG", description: ">TruSeq_Adapter_Index_22"),
  KnownAdapter(sequence: "GATCGGAAGAGCACACGTCTGAACTCCAGTCACCGTACGTTCTCGTATGCCGTCTTCTGCTTG", description: ">TruSeq Adapter, Index 22"),
  KnownAdapter(sequence: "GATCGGAAGAGCACACGTCTGAACTCCAGTCACCTTGTAATCTCGTATGCCGTCTTCTGCTTG", description: ">TruSeq_Adapter_Index_12 | >TruSeq Adapter, Index 12"),
  KnownAdapter(sequence: "GATCGGAAGAGCACACGTCTGAACTCCAGTCACGAGTGGATATCTCGTATGCCGTCTTCTGCTTG", description: ">TruSeq_Adapter_Index_23"),
  KnownAdapter(sequence: "GATCGGAAGAGCACACGTCTGAACTCCAGTCACGATCAGATCTCGTATGCCGTCTTCTGCTTG", description: ">TruSeq_Adapter_Index_9 | >TruSeq Adapter, Index 9"),
  KnownAdapter(sequence: "GATCGGAAGAGCACACGTCTGAACTCCAGTCACGCCAATATCTCGTATGCCGTCTTCTGCTTG", description: ">TruSeq_Adapter_Index_6 | >TruSeq Adapter, Index 6"),
  KnownAdapter(sequence: "GATCGGAAGAGCACACGTCTGAACTCCAGTCACGGCTACATCTCGTATGCCGTCTTCTGCTTG", description: ">TruSeq_Adapter_Index_11 | >TruSeq Adapter, Index 11"),
  KnownAdapter(sequence: "GATCGGAAGAGCACACGTCTGAACTCCAGTCACGTCCGCACATCTCGTATGCCGTCTTCTGCTTG", description: ">TruSeq_Adapter_Index_18_7"),
  KnownAdapter(sequence: "GATCGGAAGAGCACACGTCTGAACTCCAGTCACGTCCGCATCTCGTATGCCGTCTTCTGCTTG", description: ">TruSeq Adapter, Index 18"),
  KnownAdapter(sequence: "GATCGGAAGAGCACACGTCTGAACTCCAGTCACGTGAAACGATCTCGTATGCCGTCTTCTGCTTG", description: ">TruSeq_Adapter_Index_19"),
  KnownAdapter(sequence: "GATCGGAAGAGCACACGTCTGAACTCCAGTCACGTGAAACTCTCGTATGCCGTCTTCTGCTTG", description: ">TruSeq Adapter, Index 19"),
  KnownAdapter(sequence: "GATCGGAAGAGCACACGTCTGAACTCCAGTCACGTGGCCTTATCTCGTATGCCGTCTTCTGCTTG", description: ">TruSeq_Adapter_Index_20"),
  KnownAdapter(sequence: "GATCGGAAGAGCACACGTCTGAACTCCAGTCACGTGGCCTTCTCGTATGCCGTCTTCTGCTTG", description: ">TruSeq Adapter, Index 20"),
  KnownAdapter(sequence: "GATCGGAAGAGCACACGTCTGAACTCCAGTCACGTTTCGGAATCTCGTATGCCGTCTTCTGCTTG", description: ">TruSeq_Adapter_Index_21"),
  KnownAdapter(sequence: "GATCGGAAGAGCACACGTCTGAACTCCAGTCACGTTTCGGTCTCGTATGCCGTCTTCTGCTTG", description: ">TruSeq Adapter, Index 21"),
  KnownAdapter(sequence: "GATCGGAAGAGCACACGTCTGAACTCCAGTCACTAGCTTATCTCGTATGCCGTCTTCTGCTTG", description: ">TruSeq_Adapter_Index_10 | >TruSeq Adapter, Index 10"),
  KnownAdapter(sequence: "GATCGGAAGAGCACACGTCTGAACTCCAGTCACTGACCAATCTCGTATGCCGTCTTCTGCTTG", description: ">TruSeq_Adapter_Index_4 | >TruSeq Adapter, Index 4"),
  KnownAdapter(sequence: "GATCGGAAGAGCACACGTCTGAACTCCAGTCACTTAGGCATCTCGTATGCCGTCTTCTGCTTG", description: ">TruSeq_Adapter_Index_3 | >TruSeq Adapter, Index 3"),
  KnownAdapter(sequence: "GATCGGAAGAGCGGTTCAGCAGGAATGCCGAG", description: ">Illumina Paired End Adapter 2"),
  KnownAdapter(sequence: "GATCGGAAGAGCGTCGTGTAGGGAAAGAGTGT", description: ">Nextera_LMP_Read2_External_Adapter"),
  KnownAdapter(sequence: "GATCGGAAGAGCTCGTATGCCGTCTTCTGCTTG", description: ">Illumina Single End Adapter 1"),
  KnownAdapter(sequence: "GTCTCGTGGGCTCGGAGATGTGTATAAGAGACAG", description: ">Trans2"),
  KnownAdapter(sequence: "GTGACTGGAGTTCAGACGTGTGCTCTTCCGATCT", description: ">PrefixPE/2 | >PE2 | >Illumina Multiplexing PCR Primer 2.01 | >Illumina Multiplexing Read2 Sequencing Primer | >PrefixPE/2 | >PE2"),
  KnownAdapter(sequence: "TACACTCTTTCCCTACACGACGCTCTTCCGATCT", description: ">PrefixPE/1 | >PE1 | >PrefixPE/1 | >PE1"),
  KnownAdapter(sequence: "TCGGACTGTAGAACTCTGAACGTGTAGATCTCGGTGGTCGCCGTATCATT", description: ">RNA_PCR_Primer_(RP1)_part_#_15013198"),
  KnownAdapter(sequence: "TCGTCGGCAGCGTCAGATGTGTATAAGAGACAG", description: ">Trans1"),
  KnownAdapter(sequence: "TGGAATTCTCGGGTGCCAAGGAACTCCAGTCACACAGTGATCTCGTATGCCGTCTTCTGCTTG", description: ">RNA_PCR_Primer_Index_5_(RPI5)"),
  KnownAdapter(sequence: "TGGAATTCTCGGGTGCCAAGGAACTCCAGTCACACTGATATCTCGTATGCCGTCTTCTGCTTG", description: ">RNA_PCR_Primer_Index_25_(RPI25)"),
  KnownAdapter(sequence: "TGGAATTCTCGGGTGCCAAGGAACTCCAGTCACACTTGAATCTCGTATGCCGTCTTCTGCTTG", description: ">RNA_PCR_Primer_Index_8_(RPI8)"),
  KnownAdapter(sequence: "TGGAATTCTCGGGTGCCAAGGAACTCCAGTCACAGTCAAATCTCGTATGCCGTCTTCTGCTTG", description: ">RNA_PCR_Primer_Index_13_(RPI13)"),
  KnownAdapter(sequence: "TGGAATTCTCGGGTGCCAAGGAACTCCAGTCACAGTTCCATCTCGTATGCCGTCTTCTGCTTG", description: ">RNA_PCR_Primer_Index_14_(RPI14)"),
  KnownAdapter(sequence: "TGGAATTCTCGGGTGCCAAGGAACTCCAGTCACATCACGATCTCGTATGCCGTCTTCTGCTTG", description: ">RNA_PCR_Primer_Index_1_(RPI1)_2,9"),
  KnownAdapter(sequence: "TGGAATTCTCGGGTGCCAAGGAACTCCAGTCACATGAGCATCTCGTATGCCGTCTTCTGCTTG", description: ">RNA_PCR_Primer_Index_26_(RPI26)"),
  KnownAdapter(sequence: "TGGAATTCTCGGGTGCCAAGGAACTCCAGTCACATGTCAATCTCGTATGCCGTCTTCTGCTTG", description: ">RNA_PCR_Primer_Index_15_(RPI15)"),
  KnownAdapter(sequence: "TGGAATTCTCGGGTGCCAAGGAACTCCAGTCACATTCCTATCTCGTATGCCGTCTTCTGCTTG", description: ">RNA_PCR_Primer_Index_27_(RPI27)"),
  KnownAdapter(sequence: "TGGAATTCTCGGGTGCCAAGGAACTCCAGTCACCAAAAGATCTCGTATGCCGTCTTCTGCTTG", description: ">RNA_PCR_Primer_Index_28_(RPI28)"),
  KnownAdapter(sequence: "TGGAATTCTCGGGTGCCAAGGAACTCCAGTCACCAACTAATCTCGTATGCCGTCTTCTGCTTG", description: ">RNA_PCR_Primer_Index_29_(RPI29)"),
  KnownAdapter(sequence: "TGGAATTCTCGGGTGCCAAGGAACTCCAGTCACCACCGGATCTCGTATGCCGTCTTCTGCTTG", description: ">RNA_PCR_Primer_Index_30_(RPI30)"),
  KnownAdapter(sequence: "TGGAATTCTCGGGTGCCAAGGAACTCCAGTCACCACGATATCTCGTATGCCGTCTTCTGCTTG", description: ">RNA_PCR_Primer_Index_31_(RPI31)"),
  KnownAdapter(sequence: "TGGAATTCTCGGGTGCCAAGGAACTCCAGTCACCACTCAATCTCGTATGCCGTCTTCTGCTTG", description: ">RNA_PCR_Primer_Index_32_(RPI32)"),
  KnownAdapter(sequence: "TGGAATTCTCGGGTGCCAAGGAACTCCAGTCACCAGATCATCTCGTATGCCGTCTTCTGCTTG", description: ">RNA_PCR_Primer_Index_7_(RPI7)"),
  KnownAdapter(sequence: "TGGAATTCTCGGGTGCCAAGGAACTCCAGTCACCAGGCGATCTCGTATGCCGTCTTCTGCTTG", description: ">RNA_PCR_Primer_Index_33_(RPI33)"),
  KnownAdapter(sequence: "TGGAATTCTCGGGTGCCAAGGAACTCCAGTCACCATGGCATCTCGTATGCCGTCTTCTGCTTG", description: ">RNA_PCR_Primer_Index_34_(RPI34)"),
  KnownAdapter(sequence: "TGGAATTCTCGGGTGCCAAGGAACTCCAGTCACCATTTTATCTCGTATGCCGTCTTCTGCTTG", description: ">RNA_PCR_Primer_Index_35_(RPI35)"),
  KnownAdapter(sequence: "TGGAATTCTCGGGTGCCAAGGAACTCCAGTCACCCAACAATCTCGTATGCCGTCTTCTGCTTG", description: ">RNA_PCR_Primer_Index_36_(RPI36)"),
  KnownAdapter(sequence: "TGGAATTCTCGGGTGCCAAGGAACTCCAGTCACCCGTCCATCTCGTATGCCGTCTTCTGCTTG", description: ">RNA_PCR_Primer_Index_16_(RPI16)"),
  KnownAdapter(sequence: "TGGAATTCTCGGGTGCCAAGGAACTCCAGTCACCGATGTATCTCGTATGCCGTCTTCTGCTTG", description: ">RNA_PCR_Primer_Index_2_(RPI2)"),
  KnownAdapter(sequence: "TGGAATTCTCGGGTGCCAAGGAACTCCAGTCACCGGAATATCTCGTATGCCGTCTTCTGCTTG", description: ">RNA_PCR_Primer_Index_37_(RPI37)"),
  KnownAdapter(sequence: "TGGAATTCTCGGGTGCCAAGGAACTCCAGTCACCGTACGATCTCGTATGCCGTCTTCTGCTTG", description: ">RNA_PCR_Primer_Index_22_(RPI22)"),
  KnownAdapter(sequence: "TGGAATTCTCGGGTGCCAAGGAACTCCAGTCACCTAGCTATCTCGTATGCCGTCTTCTGCTTG", description: ">RNA_PCR_Primer_Index_38_(RPI38)"),
  KnownAdapter(sequence: "TGGAATTCTCGGGTGCCAAGGAACTCCAGTCACCTATACATCTCGTATGCCGTCTTCTGCTTG", description: ">RNA_PCR_Primer_Index_39_(RPI39)"),
  KnownAdapter(sequence: "TGGAATTCTCGGGTGCCAAGGAACTCCAGTCACCTCAGAATCTCGTATGCCGTCTTCTGCTTG", description: ">RNA_PCR_Primer_Index_40_(RPI40)"),
  KnownAdapter(sequence: "TGGAATTCTCGGGTGCCAAGGAACTCCAGTCACCTTGTAATCTCGTATGCCGTCTTCTGCTTG", description: ">RNA_PCR_Primer_Index_12_(RPI12)"),
  KnownAdapter(sequence: "TGGAATTCTCGGGTGCCAAGGAACTCCAGTCACGACGACATCTCGTATGCCGTCTTCTGCTTG", description: ">RNA_PCR_Primer_Index_41_(RPI41)"),
  KnownAdapter(sequence: "TGGAATTCTCGGGTGCCAAGGAACTCCAGTCACGAGTGGATCTCGTATGCCGTCTTCTGCTTG", description: ">RNA_PCR_Primer_Index_23_(RPI23)"),
  KnownAdapter(sequence: "TGGAATTCTCGGGTGCCAAGGAACTCCAGTCACGATCAGATCTCGTATGCCGTCTTCTGCTTG", description: ">RNA_PCR_Primer_Index_9_(RPI9)"),
  KnownAdapter(sequence: "TGGAATTCTCGGGTGCCAAGGAACTCCAGTCACGCCAATATCTCGTATGCCGTCTTCTGCTTG", description: ">RNA_PCR_Primer_Index_6_(RPI6)"),
  KnownAdapter(sequence: "TGGAATTCTCGGGTGCCAAGGAACTCCAGTCACGGCTACATCTCGTATGCCGTCTTCTGCTTG", description: ">RNA_PCR_Primer_Index_11_(RPI11)"),
  KnownAdapter(sequence: "TGGAATTCTCGGGTGCCAAGGAACTCCAGTCACGGTAGCATCTCGTATGCCGTCTTCTGCTTG", description: ">RNA_PCR_Primer_Index_24_(RPI24)"),
  KnownAdapter(sequence: "TGGAATTCTCGGGTGCCAAGGAACTCCAGTCACGTAGAGATCTCGTATGCCGTCTTCTGCTTG", description: ">RNA_PCR_Primer_Index_17_(RPI17)"),
  KnownAdapter(sequence: "TGGAATTCTCGGGTGCCAAGGAACTCCAGTCACGTCCGCATCTCGTATGCCGTCTTCTGCTTG", description: ">RNA_PCR_Primer_Index_18_(RPI18)"),
  KnownAdapter(sequence: "TGGAATTCTCGGGTGCCAAGGAACTCCAGTCACGTGAAAATCTCGTATGCCGTCTTCTGCTTG", description: ">RNA_PCR_Primer_Index_19_(RPI19)"),
  KnownAdapter(sequence: "TGGAATTCTCGGGTGCCAAGGAACTCCAGTCACGTGGCCATCTCGTATGCCGTCTTCTGCTTG", description: ">RNA_PCR_Primer_Index_20_(RPI20)"),
  KnownAdapter(sequence: "TGGAATTCTCGGGTGCCAAGGAACTCCAGTCACGTTTCGATCTCGTATGCCGTCTTCTGCTTG", description: ">RNA_PCR_Primer_Index_21_(RPI21)"),
  KnownAdapter(sequence: "TGGAATTCTCGGGTGCCAAGGAACTCCAGTCACTAATCGATCTCGTATGCCGTCTTCTGCTTG", description: ">RNA_PCR_Primer_Index_42_(RPI42)"),
  KnownAdapter(sequence: "TGGAATTCTCGGGTGCCAAGGAACTCCAGTCACTACAGCATCTCGTATGCCGTCTTCTGCTTG", description: ">RNA_PCR_Primer_Index_43_(RPI43)"),
  KnownAdapter(sequence: "TGGAATTCTCGGGTGCCAAGGAACTCCAGTCACTAGCTTATCTCGTATGCCGTCTTCTGCTTG", description: ">RNA_PCR_Primer_Index_10_(RPI10)"),
  KnownAdapter(sequence: "TGGAATTCTCGGGTGCCAAGGAACTCCAGTCACTATAATATCTCGTATGCCGTCTTCTGCTTG", description: ">RNA_PCR_Primer_Index_44_(RPI44)"),
  KnownAdapter(sequence: "TGGAATTCTCGGGTGCCAAGGAACTCCAGTCACTCATTCATCTCGTATGCCGTCTTCTGCTTG", description: ">RNA_PCR_Primer_Index_45_(RPI45)"),
  KnownAdapter(sequence: "TGGAATTCTCGGGTGCCAAGGAACTCCAGTCACTCCCGAATCTCGTATGCCGTCTTCTGCTTG", description: ">RNA_PCR_Primer_Index_46_(RPI46)"),
  KnownAdapter(sequence: "TGGAATTCTCGGGTGCCAAGGAACTCCAGTCACTCGAAGATCTCGTATGCCGTCTTCTGCTTG", description: ">RNA_PCR_Primer_Index_47_(RPI47)"),
  KnownAdapter(sequence: "TGGAATTCTCGGGTGCCAAGGAACTCCAGTCACTCGGCAATCTCGTATGCCGTCTTCTGCTTG", description: ">RNA_PCR_Primer_Index_48_(RPI48)"),
  KnownAdapter(sequence: "TGGAATTCTCGGGTGCCAAGGAACTCCAGTCACTGACCAATCTCGTATGCCGTCTTCTGCTTG", description: ">RNA_PCR_Primer_Index_4_(RPI4)"),
  KnownAdapter(sequence: "TGGAATTCTCGGGTGCCAAGGAACTCCAGTCACTTAGGCATCTCGTATGCCGTCTTCTGCTTG", description: ">RNA_PCR_Primer_Index_3_(RPI3)"),
  KnownAdapter(sequence: "TTTTTTTTTTAATGATACGGCGACCACCGAGATCTACAC", description: ">FlowCell1"),
  KnownAdapter(sequence: "TTTTTTTTTTCAAGCAGAAGACGGCATACGA", description: ">FlowCell2"),
  KnownAdapter(sequence: "AAGTCGGAGGCCAAGCGGTCTTAGGAAGACAA", description: ">MGI/BGI adapter (forward)"),
  KnownAdapter(sequence: "AAGTCGGATCGTAGCCATGTCGTTCTGTGAGCCAAGGAGTTG", description: ">MGI/BGI adapter (reverse)"),
  KnownAdapter(sequence: "AACTGTAGGCACCATCAAT", description: ">QIASeq miRNA adapter")
]

